services:
  - type: web
    name: automatisch-main
    env: docker
    dockerfilePath: ./docker/Dockerfile
    dockerContext: .
    repo: https://github.com/SPPROF12/automatisch
    autoDeploy: false
    envVars:
      - key: HOST
        fromService:
          name: automatisch-main
          type: web
          envVarKey: RENDER_EXTERNAL_HOSTNAME
      - key: POSTGRES_HOST
        value: your-external-database-host
      - key: POSTGRES_PORT
        value: your-external-database-port
      - key: POSTGRES_DATABASE
        value: your-external-database-name
      - key: POSTGRES_USERNAME
        value: your-external-database-username
      - key: POSTGRES_PASSWORD
        value: your-external-database-password
      - key: REDIS_HOST
        value: your-external-redis-host
      - key: REDIS_PORT
        value: your-external-redis-port
      - fromGroup: common-env-vars
  - type: worker
    name: automatisch-worker
    env: docker
    dockerfilePath: ./docker/Dockerfile
    dockerContext: .
    repo: https://github.com/SPPROF12/automatisch
    autoDeploy: false
    envVars:
      - key: WORKER
        value: true
      - key: HOST
        fromService:
          name: automatisch-main
          type: web
          envVarKey: RENDER_EXTERNAL_HOSTNAME
      - key: POSTGRES_HOST
        value: your-external-database-host
      - key: POSTGRES_PORT
        value: your-external-database-port
      - key: POSTGRES_DATABASE
        value: your-external-database-name
      - key: POSTGRES_USERNAME
        value: your-external-database-username
      - key: POSTGRES_PASSWORD
        value: your-external-database-password
      - key: REDIS_HOST
        value: your-external-redis-host
      - key: REDIS_PORT
        value: your-external-redis-port
      - fromGroup: common-env-vars

envVarGroups:
  - name: common-env-vars
    envVars:
      - key: APP_ENV
        value: production
      - key: PROTOCOL
        value: https
      - key: PORT
        value: 443
      - key: ENCRYPTION_KEY
        generateValue: true
      - key: WEBHOOK_SECRET_KEY
        generateValue: true
      - key: APP_SECRET_KEY
        generateValue: true
